apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logistis
spec:
  selector:
    matchLabels:
      app: logistis
  serviceName: logistis
  replicas: 1
  template:
    metadata:
      labels:
        app: logistis
    spec:
      containers:
        - image: simple-kubernetes-webhook:latest
          imagePullPolicy: Always
          name: logistis
          command: ["logistis"]
          args:
          - -cert-file
          - /etc/admission-webhook/tls/tls.crt
          - -key-file
          - /etc/admission-webhook/tls/tls.key
          - -db
          - /data/logistis
          volumeMounts:
            - name: tls
              mountPath: "/etc/admission-webhook/tls"
              readOnly: true
            - name: logistis-vol
              mountPath: "/data"
      volumes:
        - name: tls
          secret:
            secretName: logistis-tls
  volumeClaimTemplates:
  - metadata:
      name: logistis-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
