apiVersion: v1
data:
  tls.crt: {{ .Values.tls.cert }}
  tls.key: {{ .Values.tls.key }}
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ include "logistis.fullname" . }}-tls
type: kubernetes.io/tls
