apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "simple-kubernetes-webhook.acme.com"
webhooks:
  - name: "simple-kubernetes-webhook.acme.com"
    failurePolicy: Ignore
    rules:
      - apiGroups: ["", "apps"]
        apiVersions: ["v1"]
        operations: ["*"]
        resources: ["deployments", "statefulsets", "configmaps", "secrets"]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: simple-kubernetes-webhook
        path: /
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKRENDQWd5Z0F3SUJBZ0lVT0hXUmFUckRhMGpoYnRVQWxyVUdwdGNNL0o0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd01URUxNQWtHQTFVRUJoTUNRVlV4SWpBZ0JnTlZCQU1NR1hOcGJYQnNaUzFyZFdKbGNtNWxkR1Z6TFhkbApZbWh2YjJzd0hoY05Nakl3T0RFeU1qRTBNekUyV2hjTk1qTXdPREV5TWpFME16RTJXakF4TVFzd0NRWURWUVFHCkV3SkJWVEVpTUNBR0ExVUVBd3daYzJsdGNHeGxMV3QxWW1WeWJtVjBaWE10ZDJWaWFHOXZhekNDQVNJd0RRWUoKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWYzZXNwT0llVzVYcFJZYUYzYlAyK2xuMFh3MWV2agpPNjYybFI2Q0xNWksrMml5TmFvMk9sd1VIN1IvNmV2dWdtY0JrRXl3QUxPZFZndHhYNlA4OVFlMEM1UkUyUy9xCmE0NVp2Sk5YWjFpQ1FzdU5UalJrZ1AxTnRqS2hoY3M4Znl4bGJVZ1FwaXR4TE9oS1VlN0kyRFlWMGQxYnV5cjUKUXRWVmFRVStnZ01xRnNra3BibnBzcjUxRDNKeUhJSnVRZTZUS294Zk0wR2htV0dhOWV5VTkzVVB1QjZ1TGJBUwoxdWU1dCtzaHZXcUcxNDdWWHJNaFVFUmMvcm4rYjJ3R0NvcE0xOXdTOHhPSVlCUS9qMUlBSjI4UDhzRytyWUttCjd0WTY0Ni9UZk9NQmFObU9IRDBLbEpPSFhrNGFRbFBXQVh4VUtsczFqdUJ5Q04wYnRQT04xTVVDQXdFQUFhTTAKTURJd01BWURWUjBSQkNrd0o0SWxjMmx0Y0d4bExXdDFZbVZ5Ym1WMFpYTXRkMlZpYUc5dmF5NWtaV1poZFd4MApMbk4yWXpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUR6bUxoQ2RadlRpRFliL2ZDOVp3QzZySzhjV1oxeXNxCmN6aW9FcVhwVVExeGcvM1JQYmNid2o0UWg2L3pSQmlUZTZVdkhUY2hXWXJ2Y3crc2hjUGxwMlUrMFcrVnVseEQKWW51dTRua2xJMlUxWjkrdm5SRzBMV1lLTGxjUlFMMFQ1VmkwempmU2pubG9ONkVTNGwrNVFWSEFZQjJSaFpHTgphOUZvSmNhWVBFTTdNMWVqZWZ1dENtWFNwKytRSFRXODlmcEp4YzVmQTVwaHgrQ0h5eHhrK3cxSVVvTy84ZkxQClpRODMwbC9MTlh2S3ZIbTBONWR1eXF5RHc0WWF3ZDdDVjlPVHB6ZXZKc3lGOGVpY0xDaGsrLzViVTE0a3dERHUKVzBBNHRTcXdOY3g5SG1MaUhSaWM3Vnk0MHQ3andaT0x5czRCWnU1cUYvRWtuKzZQUFVkUnFBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2
